name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # https://github.com/actions/virtual-environments/tree/main/images/macos
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

  MACOS_SDK: macosx10.15
  MACOS_DEST: "arch=x86_64"

  IOS_SDK: iphonesimulator14.0
  IOS_DEST: "OS=14.0,name=iPhone 11"

jobs:
  job-main:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v1

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: list simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list

      - name: SPM generate xcodeproj
        run: swift package generate-xcodeproj

      - name: Build iOS
        run: |
          set -o pipefail
          xcodebuild clean build -sdk "$IOS_SDK" -destination "$IOS_DEST" | xcpretty -c

      - name: Build macOS
        run: |
          set -o pipefail
          xcodebuild clean build -sdk "$MACOS_SDK" -destination "$MACOS_DEST" | xcpretty -c
