# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'Package*'
      - 'Sources/**/*.*'
      - 'Tests/**/*.*'
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
  IOS_DEST: "platform=iOS Simulator,name=iPhone 13 Mini,OS=latest"

  SCHEME: HexedBitsColors

jobs:
  main:
    name: SwiftPM Build
    runs-on: macOS-11
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: list simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list

      - name: macOS build
        run: swift build

      - name: iOS build
        run: |
          set -o pipefail
          xcodebuild build -scheme "$SCHEME" -destination "$IOS_DEST" | xcpretty -c
