# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'Package*'
      - 'Sources/**/*.*'
      - 'Tests/**/*.*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'Package*'
      - 'Sources/**/*.*'
      - 'Tests/**/*.*'

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

  IOS_SDK: iphonesimulator14.4
  IOS_DEST: "OS=14.4,name=iPhone 12 Mini"

jobs:
  main:
    name: SwiftPM Build
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: list simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list

      - name: swift build
        run: swift build

      - name: iOS build
        run: |
          set -o pipefail
          swift package generate-xcodeproj
          xcodebuild clean build -sdk "$IOS_SDK" -destination "$IOS_DEST" | xcpretty -c
